language: python
python:
  - "3.6"
sudo: required
install: 
  - sh ci/install_requirements.sh

env:
  global:
  - TRAVIS_INTEGRATION=TRUE

addons:
  sonarcloud:
    organization: "rosesthen00b-github"
  firefox: "61.0"

before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.21.0/geckodriver-v0.21.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.21.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver

script: 
  - sh ci/run_unit_tests.sh
  - sh ci/run_integration_tests.sh

after_success:
  - sh ci/sonar_qube.sh
  - coveralls
  - codecov




