language: python
python:
  - "3.6"
install: 
  - pip install -r integration-requirements.txt
  - pip install coveralls
  - pip install codecov

script: py.test --cov=mysite

after_success:
  - coveralls
  - codecov 
