language: python
python:
  - "3.6"
php:
  - 7.1.9
sudo: required

install: 
  - sh ci/install_requirements.sh

env:
  global:
  - TRAVIS_INTEGRATION=TRUE

addons:
  sonarcloud:
    organization: "rosesthen00b-github"
  firefox: "61.0"

services:
  - mysql

before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.21.0/geckodriver-v0.21.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.21.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
  - mysql -e 'CREATE DATABASE testdb;'

jobs:
  include:
    - stage: butler_offline::unit_test
      script: sh ci/run_unit_tests.sh
    - stage: butler_offline::selenium_test
      script: sh ci/run_integration_tests.sh
    - stage: butler_online
      script: sh ci/online.sh
    - stage: notify_ci_services
      script: sh ci/notify_integration_services.sh


