language: python
python:
  - "3.6"
install: 
  - pip install -r integration-requirements.txt
  - pip install coveralls
  - pip install codecov

addons:
  sonarcloud:
    organization: "rosesthen00b-github"


script: 
  - cd mysite && py.test --cov=mysite && cd ..
  - sonar-scanner -Dsonar.login=$SONAR

after_success:
  - coveralls
  - codecov 
