language: python
python:
  - "3.6"
sudo: required
install: 
  - sh ci/install_requirements.sh

env:
  global:
  - TRAVIS_INTEGRATION=TRUE

addons:
  sonarcloud:
    organization: "rosesthen00b-github"


script: 
  - sh ci/run_unit_tests.sh
  - sh ci/run_integration_tests.sh

after_success:
  - sh ci/sonar_qube.sh
  - coveralls
  - codecov




