language: python
python:
  - "3.6"
install: 
  - pip install -r integration-requirements.txt
  - pip install coveralls
script: py.test --cov=mysite

after_success:
  - coveralls
  - pip install codecov && codecov -t $CODECOV
 
