language: python
python:
  - "3.6"
install: 
  - pip install -r integration-requirements.txt
  - pip install coveralls
  - pip install codecov
  - sudo apt-get install chromium-browser

env:
  global:
  - TRAVIS_INTEGRATION=TRUE

addons:
  sonarcloud:
    organization: "rosesthen00b-github"


script: 
  - py.test --cov=mysite mysite
  - cd mysite && python manage.py runserver > build.log &
  - cd selenium_tests && pytest && cd ..
  - sonar-scanner -Dsonar.login=$SONAR

after_success:
  - coveralls
  - codecov 
