version: '3'
services:
  static-web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./src:/www:ro
      - ./site.conf:/etc/nginx/conf.d/default.conf:ro
    env_file:
      - db.env
    restart: unless-stopped


  php-fpm:
    build: php-fpm-image
    volumes:
      - ./src/:/www/:ro
    env_file:
      - db.env
    restart: unless-stopped

  db:
    image: mariadb
    restart: always
    volumes:
      - db:/var/lib/mysql
    env_file:
      - db.env
    restart: unless-stopped


volumes:
  db:

